use_frameworks!

platform :ios, '9.3'

target 'PINTextFieldView_Example' do
  pod 'PINTextFieldView', :path => '../'

  target 'PINTextFieldView_ExampleTests' do
    pod 'Quick'
    pod 'Nimble'
  end
end
